# -*- coding: utf-8 -*-
"""GAME-3 Missionaries 3 Cannibals crossing the River.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lj8P-dg4KJ0P2TxfD0s4wLh9Geypvben
"""

boat_side = "Right"
missionaries_on_right = 3
cannibals_on_right = 3
missionaries_on_left = 0
cannibals_on_left = 0


def display_board(boat_position, missionaries_on_left, cannibals_on_left, missionaries_on_right, cannibals_on_right):
    left_bank = ""
    for _ in range(missionaries_on_left):
        left_bank += 'M'
    for _ in range(cannibals_on_left):
        left_bank += 'C'

    right_bank = ""
    for _ in range(missionaries_on_right):
        right_bank += 'M'
    for _ in range(cannibals_on_right):
        right_bank += 'C'

    if boat_position == "Left":
        print("M =",missionaries_on_left, "C =",cannibals_on_left, "|B-----|", "M =",missionaries_on_right, "C =",cannibals_on_right)
    else:
        print("M =",missionaries_on_left, "C =",cannibals_on_left, "|-----B|", "M =",missionaries_on_right, "C =",cannibals_on_right)


display_board(boat_side, missionaries_on_left, cannibals_on_left, missionaries_on_right, cannibals_on_right)


while True:

    missionaries_to_move = int(input("Enter number of missionaries to move: "))
    cannibals_to_move = int(input("Enter number of cannibals to move: "))


    if missionaries_to_move + cannibals_to_move < 1 or missionaries_to_move + cannibals_to_move > 2:
        print("Invalid move")#Boat must carry 1 or 2 people.
        continue

    if boat_side == "Right":
        if missionaries_to_move > missionaries_on_right or cannibals_to_move > cannibals_on_right:
            print("Invalid move")#Not enough people on the right side.


        missionaries_on_right -= missionaries_to_move
        cannibals_on_right -= cannibals_to_move
        missionaries_on_left += missionaries_to_move
        cannibals_on_left += cannibals_to_move
        boat_side = "Left"

    elif boat_side == "Left":
        if missionaries_to_move > missionaries_on_left or cannibals_to_move > cannibals_on_left:
            print("Invalid move")# Not enough people on the left side.


        missionaries_on_left -= missionaries_to_move
        cannibals_on_left -= cannibals_to_move
        missionaries_on_right += missionaries_to_move
        cannibals_on_right += cannibals_to_move
        boat_side = "Right"

    if (missionaries_on_right > 0 and missionaries_on_right < cannibals_on_right) or (missionaries_on_left > 0 and missionaries_on_left < cannibals_on_left):
        print("YOU LOSE!")
        break


    display_board(boat_side, missionaries_on_left, cannibals_on_left, missionaries_on_right, cannibals_on_right)

    if missionaries_on_left == 3 and cannibals_on_left == 3:
        print("YOU WIN!")
        break

print("Game Over")